#! /usr/bin/env bash

# Make sure to set C9TOOLSROOT to a directory that you have full access to!

export C9TOOLSROOT=${C9TOOLSROOT:=~/.c9tools}

# -- main

# if target directory exists, this is just an update (bin only)

if test -f ${C9TOOLSROOT}/etc/org_access
then
  echo "Updating tools --> only copying distribution/bin to ${C9TOOLSROOT}/bin"
  cp -rp distribution/bin/* ${C9TOOLSROOT}/bin
  exit 0
fi

# first time install starts here

echo "Installing tools in ${C9TOOLSROOT}"
mkdir -p ${C9TOOLSROOT}/bin
mkdir -p ${C9TOOLSROOT}/etc

cp -rp distribution/bin/* ${C9TOOLSROOT}/bin
test -f ${C9TOOLSROOT}/etc/org_access || cp -rp distribution/etc/* ${C9TOOLSROOT}/etc

echo "Setting up profile"

# -- create .profile_c9tools

cat <<EOF > ~/.profile_c9tools
# Config root of tools tree

export C9TOOLSROOT=${C9TOOLSROOT}

# Extend PATH & source functions

export MAKEFILES=${C9TOOLSROOT}/etc/Makefile.rules

export PATH="\$PATH:\${C9TOOLSROOT}/bin"
[[ -s "${C9TOOLSROOT}/bin/_functions" ]] && source "${C9TOOLSROOT}/bin/_functions" && c9toolsinit

EOF

# -- add c9tools profile to shell profiles

grep -q '.profile_c9tools' ~/.bash_profile || echo 'source ~/.profile_c9tools' >> ~/.bash_profile
grep -q '.profile_c9tools' ~/.profile      || echo 'source ~/.profile_c9tools' >> ~/.profile
