#! /usr/bin/env bash

# Make sure to set C9TOOLSROOT to a directory that you have full access to!

export C9TOOLSROOT=${C9TOOLSROOT:=~/.c9tools}

ORG_ACCESS_FILE=${C9TOOLSROOT}/etc/org_access
if !test -z ${AWSENV} ; then
  ORG_ACCESS_FILE=${ORG_ACCESS_FILE}.${AWSENV}
fi

# -- main

# if target directory exists, this is just an update (bin only)

if ! test -d ${C9TOOLSROOT}/etc
then
  echo "c9tools not installed in ${C9TOOLSROOT}/bin"
  echo "run install before setup!"
  exit 1
fi

test -f ${ORG_ACCESS_FILE} && source ${ORG_ACCESS_FILE}

echo "Configuring ${AWS_ENV:-default} environment"
echo -n "Enter 12 digit AWS accountnumber of Organization Master Account [${ORG_MASTER_ACCOUNT}] : "
read accountId
ORG_MASTER_ACCOUNT=${accountId:-${ORG_MASTER_ACCOUNT}}
echo -n "Enter name for CrossAccount Role [${ORG_ACCOUNT_ACCESS_ROLE}]: "
read oar
ORG_ACCOUNT_ACCESS_ROLE=${oar:-${ORG_ACCOUNT_ACCESS_ROLE}} 

echo "ORG_MASTER_ACCOUNT=${ORG_MASTER_ACCOUNT}" >> ${ORG_ACCESS_FILE}
echo "ORG_ACCOUNT_ACCESS_ROLE=${ORG_ACCOUNT_ACCESS_ROLE}" >> ${ORG_ACCESS_FILE}

echo "Review ${ORG_ACCESS_FILE} for full cross account access role setup"
